version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - "> 7.11.0, < 7.12"
  - dependency-name: babel-loader
    versions:
    - "> 8.1.0, < 8.2"
  - dependency-name: "@babel/preset-env"
    versions:
    - "> 7.11.0, < 8"
  - dependency-name: nativescript-vue
    versions:
    - "> 2.7.1, < 3"
  - dependency-name: nativescript-vue-template-compiler
    versions:
    - "> 2.7.1, < 3"
  - dependency-name: tns-core-modules
    versions:
    - "> 6.5.12, < 6.6"
  - dependency-name: vue-loader
    versions:
    - "> 15.9.3, < 16"
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
